FROM nginx:alpine
COPY /nginx/conf.d/default.conf /etc/nginx/conf.d/
COPY /nginx/sites-enable/ /etc/nginx/conf.d/
RUN mkdir /etc/nginx/ssl && mkdir /var/www/html/static
COPY /nginx/ssl/ /etc/nginx/ssl/
COPY /nginx/static/ /var/www/html/static/
