FROM nginx:alpine

RUN mkdir /etc/nginx/ssl && mkdir /etc/nginx/sites-enable

COPY /nginx/conf.d/default.conf /etc/nginx/conf.d/
COPY /nginx/sites-enable/ /etc/nginx/sites-enable/

#&& mkdir -p /www/html/static
COPY /nginx/ssl/ /etc/nginx/ssl/
#COPY /nginx/static/ /www/html/static/
